swagger: "2.0"
info:
  title: Go Pro API
  description: 这是一个基于Golang开发的Web服务器
  version: 1.0.0
  termsOfService: NO terms of service
  contact:
    email: summng@qq.com
  license:
    name: The Apache License, Version 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /account/login:
    post:
      tags:
      - account
      description: 手机/邮箱/昵称登录
      operationId: AccountController.登录
      parameters:
      - in: body
        name: body
        description: 账号<br>密码<br>区号
        required: true
        schema:
          $ref: '#/definitions/.LoginParam'
  /account/loginWithCode:
    post:
      tags:
      - account
      description: 手机验证码登录
      operationId: AccountController.验证码登录
      parameters:
      - in: body
        name: body
        description: 手机账号<br>验证码
        required: true
        schema:
          $ref: '#/definitions/.LoginWithCodeParam'
  /account/sendAuthEmail:
    post:
      tags:
      - account
      description: 发送认证邮件和忘记密码
      operationId: AccountController.发送验证邮件
      parameters:
      - in: body
        name: body
        description: 账号Id<br>邮件地址<br>邮件类型：1=邮箱认证，2=忘记密码
        required: true
        schema:
          $ref: '#/definitions/.SendAuthEmailParam'
      responses:
        "200":
          description: '{string} {"b" : 1}'
  /account/sendEmail:
    post:
      tags:
      - account
      description: 发送Html邮件
      operationId: AccountController.发送邮件
      parameters:
      - in: body
        name: body
        description: 收件人<br>收件内容<br>标题
        required: true
        schema:
          $ref: '#/definitions/.SendEmailParam'
      responses:
        "200":
          description: '{string} {"b" : 1}'
  /account/sendSmsCode:
    post:
      tags:
      - account
      description: 发送短信验证码
      operationId: AccountController.发送短信验证码
      parameters:
      - in: body
        name: body
        description: 手机号码
        required: true
        schema:
          $ref: '#/definitions/.SendSmsCodeParam'
      responses:
        "200":
          description: '{string} {"b" : 1}'
  /stream/createStream/{url}:
    get:
      tags:
      - stream
      description: 创建一条相对时间的直播流
      operationId: StreamController.创建直播流
      parameters:
      - in: path
        name: url
        description: 收件人<br>收件内容<br>标题
        required: true
        schema:
          $ref: '#/definitions/.CreateStreamParam'
      responses:
        "200":
          description: '{string} {"b" : 1}'
definitions:
  .CreateStreamParam:
    type: object
  .LoginParam:
    type: object
  .LoginWithCodeParam:
    type: object
  .SendAuthEmailParam:
    type: object
  .SendEmailParam:
    type: object
  .SendSmsCodeParam:
    type: object
